- name: Deploy
  uses: LGinC/portainer-stack-deploy@1.0
  with:
    serverurl: ${{ secrets.PORTAINER_URL }}
    username: ${{ secrets.PORTAINER_ACCOUNT }}
    password: ${{ secrets.PORTAINER_PASSWORD }}
    endpointId: 2
    stackname: enime-api
    docker_compose_path: deploy/docker-compose.yaml
    repo_username: ${{ secrets.REPO_USERNAME }}
    repo_password: ${{ secrets.REPO_PASSWORD }}
